name: whisperX
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch==2.3.1
  - torchaudio==2.3.1
  - pytorch-cuda=11.8
  - torchvision==0.18.1
  - pip:
    - git+https://github.com/m-bain/whisperx.git
